name: Validating API
on:
  workflow_dispatch:
  push:
    branches: ["Python"]
  pull_request:
    branches: ["Python"]

jobs:
  run-tests:
    uses: Raghavendiran-2002/API-Validation/.github/workflows/github_actions.yml@main
    secrets: inherit
    with:
      #YOUR_MAIL_ID: <your@mail.com>
      YOUR_MAIL_ID: raghavendiran222222@gmail.com
