name: Validating API
on:
  workflow_dispatch:
  push:
    branches: ["Node"]
  pull_request:
    branches: ["Node"]

jobs:
  run-tests:
    uses: Raghavendiran-2002/APITester/.github/workflows/github_actions.yml@main
    secrets: inherit
    with:
      #YOUR_MAIL_ID: <your@mail.com>
      YOUR_MAIL_ID: sample@gmail.com
